'use client';
import { useState } from 'react';
import { saveSettings, testComputerConnection } from '../lib/api';

export default function ComputerSettings({ connection, url, configured, loaded, onSaved }) {
  const [mode,setMode]=useState(connection || 'deployment');
  const [address,setAddress]=useState(url || '');
  const [token,setToken]=useState('');
  const [busy,setBusy]=useState(false);
  const [notice,setNotice]=useState(null);
  async function save(event) {
    event.preventDefault();setBusy(true);setNotice(null);
    try { const result=await saveSettings({computer_connection:mode,computer_remote_url:address.trim(),computer_remote_token:token.trim()});setToken('');onSaved(result);setNotice({text:'Computer connection saved.'}); }
    catch(error){setNotice({error:true,text:error.message});}finally{setBusy(false);}
  }
  return <section className="settings-group space-y-5"><div><h2>Computer</h2><p className="settings-description">Connect a Windows desktop for Poka to work in.</p></div>
    <form onSubmit={save} className="space-y-5"><fieldset disabled={!loaded || busy} className="space-y-5">
      <label className="block">Computer provider<select className="settings-input mt-2" value={mode} onChange={e=>setMode(e.target.value)}><option value="deployment">Deployment provider</option><option value="windows">Windows server</option></select></label>
      {mode==='windows' && <>
        <a className="soft-button" href="/downloads/Poka-Windows-Agent-0.3.6.zip" download>Download Windows Agent setup</a>
        <p className="text-sm text-zinc-400 leading-6">Install Poka Windows Agent on your server and verify the Windows account during setup. Then enter the agent connection here.</p>
        <label className="block">Windows agent address<input type="url" required className="settings-input mt-2" value={address} onChange={e=>setAddress(e.target.value)} placeholder="https://windows-agent.example.com:8765" /></label>
        <p className="text-xs text-zinc-500">Use HTTP localhost only when the Poka backend runs on that Windows machine.</p>
        <label className="block">Agent access token<input type="password" autoComplete="new-password" required={!configured} className="settings-input mt-2" value={token} onChange={e=>setToken(e.target.value)} placeholder={configured?'Stored securely — leave blank to keep':'Token generated by Windows setup'} /></label>
        <p className="text-xs text-zinc-500">Encrypted in your workspace. This is the agent token; your Windows password stays on the Windows server.</p>
        <div className="app-notice">Windows needs Desktop Experience and a signed-in, unlocked account for browser, display, and input. One agent shares one desktop across assistants.</div>
      </>}
      <div className="flex gap-3 flex-wrap"><button className="primary-button" type="submit">{busy?'Working…':'Save connection'}</button>{mode==='windows' && <button className="soft-button" type="button" onClick={async()=>{setBusy(true);setNotice(null);try{const result=await testComputerConnection();setNotice({error:!result.desktop_available,text:result.message+(result.account ? ` Account: ${result.account}.`:'')});}catch(error){setNotice({error:true,text:error.message});}finally{setBusy(false);}}}>Check saved connection</button>}</div>
      <p className="text-xs text-zinc-500">Stop running computers before switching providers. Save changes before checking.</p>
    </fieldset></form>
    {notice && <p role={notice.error?'alert':'status'} className={`text-sm ${notice.error?'text-red-400':'text-emerald-400'}`}>{notice.text}</p>}
  </section>;
}
