'use client';
import { useEffect, useState } from 'react';
import { FiPlus, FiCheckSquare, FiGrid, FiSearch, FiTrash2, FiX, FiFileText, FiGlobe, FiImage, FiDownload, FiArrowRight } from 'react-icons/fi';

function useLocalCollection(key) {
  const [items, setItems] = useState([]);
  const [ready, setReady] = useState(false);
  const [error, setError] = useState('');
  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem(key) || '[]'); if (Array.isArray(saved)) setItems(saved); } catch { setError('Could not read saved items.'); } setReady(true); }, [key]);
  const update = next => { try { localStorage.setItem(key, JSON.stringify(next)); setItems(next); setError(''); return true; } catch { setError('Could not save. Local storage may be full.'); return false; } };
  return [items, update, ready, error];
}
function PanelHeader({ title, description, children }) { return <header className="panel-header"><div><h1>{title}</h1><p>{description}</p></div>{children}</header>; }
export function GoalsPanel() {
  const [goals, save, ready, error] = useLocalCollection('poka_goals_v1');
  const [title, setTitle] = useState('');
  const [category, setCategory] = useState('Productivity');
  const active = goals.filter(g => !g.completed);
  return <div className="workspace-page"><PanelHeader title="Goals" description="A little focus for the things that matter." />
    {error && <p role="alert" className="text-red-400">{error}</p>}
    <h2 className="tracking-heading"><span />{active.length ? `Tracking · ${active.length}` : 'Ready when you are'}</h2>
    {!ready ? <p role="status">Loading goals…</p> : !goals.length ? <div className="panel-empty"><FiCheckSquare /><h3>What would you like to work toward?</h3><p>Add a goal and check it off when it’s done.</p></div> : <div className="goal-list">{goals.map(goal => <div key={goal.id} className="goal-row"><input type="checkbox" aria-label={`Complete ${goal.title}`} checked={goal.completed} onChange={() => save(goals.map(g => g.id === goal.id ? { ...g, completed: !g.completed } : g))} /><div><p className={goal.completed ? 'line-through text-zinc-500' : ''}>{goal.title}</p><span>{goal.category} · {goal.completed ? 'Completed' : 'In progress'}</span></div><button className="icon-button ml-auto" title="Delete goal" aria-label={`Delete ${goal.title}`} onClick={() => save(goals.filter(g => g.id !== goal.id))}><FiTrash2 /></button></div>)}</div>}
    <form className="goal-form" onSubmit={e => { e.preventDefault(); if (!title.trim()) return; if (save([...goals, { id: crypto.randomUUID(), title: title.trim(), category, completed: false }])) setTitle(''); }}><h2 className="text-xl font-semibold mb-5">Create a goal</h2><label className="field-label">What do you want to achieve?<input required value={title} onChange={e => setTitle(e.target.value)} className="setup-input" placeholder="e.g. Launch my portfolio" /></label><div className="flex gap-3 mt-4"><select aria-label="Goal category" className="setup-input" value={category} onChange={e => setCategory(e.target.value)}>{['Health', 'Relationships', 'Finance', 'Career', 'Interests', 'Productivity', 'Something else'].map(c => <option key={c}>{c}</option>)}</select><button disabled={!ready} className="primary-button shrink-0"><FiPlus /> Add goal</button></div><p className="text-xs text-zinc-500 mt-4">Goals are a personal checklist saved on this device.</p></form>
  </div>;
}
export function ArtifactsPanel() {
  const [items, save, ready, error] = useLocalCollection('poka_artifacts_v1');
  const [filter, setFilter] = useState('all');
  const [search, setSearch] = useState('');
  const [draft, setDraft] = useState(null);
  const filtered = items.filter(i => (filter === 'all' || i.type === filter) && `${i.title} ${i.content}`.toLowerCase().includes(search.toLowerCase()));
  const download = item => { const blob = new Blob([item.content], { type: 'text/plain' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `${item.title.replace(/[^a-z0-9 _-]/gi, '') || 'document'}.md`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };
  return <div className="artifact-layout"><aside className="artifact-sidebar"><label className="sidebar-search"><FiSearch /><input aria-label="Search artifacts" placeholder="Search" value={search} onChange={e => setSearch(e.target.value)} /></label><p className="sidebar-label">Artifacts</p>{[['all', 'All artifacts', FiGrid], ['document', 'Documents', FiFileText], ['web', 'Web artifacts', FiGlobe]].map(([id, label, Icon]) => <button className={`artifact-filter ${filter === id ? 'selected' : ''}`} key={id} onClick={() => setFilter(id)}><Icon />{label}</button>)}<p className="sidebar-label">Media</p>{[['image', 'Images'], ['video', 'Videos'], ['audio', 'Podcasts / audio']].map(([id, label]) => <button key={id} className={`artifact-filter ${filter === id ? 'selected' : ''}`} onClick={() => setFilter(id)}><FiImage />{label}</button>)}<div className="mt-auto p-3 text-xs text-zinc-500">Saved locally on this device</div></aside>
    <div className="workspace-page flex-1 min-w-0"><PanelHeader title={filter === 'all' ? 'All artifacts' : filter === 'web' ? 'Web artifacts' : filter === 'image' ? 'Images' : filter === 'video' ? 'Videos' : filter === 'audio' ? 'Podcasts / audio' : 'Documents'} description="Keep your work together." ><button className="primary-button" disabled={!ready} onClick={() => setDraft({ title: '', type: 'document', content: '' })}><FiPlus />Create an artifact</button></PanelHeader>
      {error && <p role="alert" className="text-red-400">{error}</p>}{!ready ? <p role="status">Loading artifacts…</p> : !filtered.length ? <div className="panel-empty artifact-empty"><FiGrid /><h3>{search ? 'No matching artifacts' : 'No artifacts yet'}</h3><p>{search ? 'Try another search.' : 'Create a document or save a web link to get started.'}</p></div> : <div className="artifact-grid">{filtered.map(item => <article className="artifact-card" key={item.id}>{item.type === 'web' ? <FiGlobe /> : item.type === 'document' ? <FiFileText /> : <FiImage />}{item.type === 'image' && <img src={item.content} alt={item.title} className="rounded-xl w-full h-36 object-cover mb-4" />}{item.type === 'video' && <video src={item.content} controls preload="metadata" className="rounded-xl w-full mb-4" />}{item.type === 'audio' && <audio src={item.content} controls preload="none" className="w-full mb-4" />}<button onClick={() => setDraft(item)} className="block text-left w-full"><h3>{item.title}</h3><p>{item.content.slice(0, 150)}</p></button><div className="flex gap-2 mt-5">{item.type !== 'document' ? <a className="soft-button" href={item.content} target="_blank" rel="noreferrer">Open link <FiArrowRight /></a> : <button className="soft-button" onClick={() => download(item)}><FiDownload /> Export</button>}<button className="icon-button ml-auto" aria-label={`Delete ${item.title}`} onClick={() => save(items.filter(i => i.id !== item.id))}><FiTrash2 /></button></div></article>)}</div>}
    </div>
    {draft && <div className="modal-backdrop"><section className="workspace-modal" role="dialog" aria-modal="true" aria-labelledby="artifact-editor"><button className="icon-button absolute top-5 right-5" onClick={() => setDraft(null)} aria-label="Close editor"><FiX /></button><h2 id="artifact-editor" className="text-2xl font-semibold mb-6">{draft.id ? 'Edit artifact' : 'Create an artifact'}</h2><form className="space-y-5" onSubmit={e => { e.preventDefault(); if (draft.type !== 'document') { try { const url = new URL(draft.content); if (!['http:', 'https:'].includes(url.protocol)) throw new Error(); } catch { return; } } const item = { ...draft, id: draft.id || crypto.randomUUID(), updatedAt: new Date().toISOString() }; if (save(draft.id ? items.map(i => i.id === draft.id ? item : i) : [...items, item])) setDraft(null); }}><label className="field-label">Title<input required className="setup-input" value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} autoFocus /></label><label className="field-label">Type<select className="setup-input" value={draft.type} onChange={e => setDraft({ ...draft, type: e.target.value })}><option value="document">Document</option><option value="web">Web link</option><option value="image">Image URL</option><option value="video">Video URL</option><option value="audio">Audio URL</option></select></label><label className="field-label">{draft.type !== 'document' ? 'URL (http or https)' : 'Content'}{draft.type !== 'document' ? <input type="url" required pattern="https?://.*" value={draft.content} onChange={e => setDraft({ ...draft, content: e.target.value })} className="setup-input" placeholder="https://" /> : <textarea required rows={8} className="setup-input" value={draft.content} onChange={e => setDraft({ ...draft, content: e.target.value })} placeholder="Write or paste your document…" />}</label><button className="primary-button w-full justify-center">Save artifact</button></form></section></div>}
  </div>;
}
export function SearchPanel({ bots, onSelectBot }) {
  const [query, setQuery] = useState('');
  const [results, setResults] = useState([]);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  return <div className="workspace-page"><PanelHeader title="Search" description="Find a conversation in your workspace." /><form className="global-search" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { const { fetchChatHistory } = await import('../lib/api'); const found = await Promise.all(bots.map(async bot => { const history = await fetchChatHistory(bot.id); return { bot, matches: history.filter(m => m.text?.toLowerCase().includes(query.toLowerCase())) }; })); setResults(found.filter(r => r.matches.length || r.bot.name.toLowerCase().includes(query.toLowerCase()))); } catch { setError('Could not search your conversations.'); } finally { setBusy(false); } }}><FiSearch /><input aria-label="Search conversation text" required value={query} onChange={e => setQuery(e.target.value)} placeholder="Search messages and assistants" autoFocus /><button className="soft-button" disabled={busy}>{busy ? 'Searching…' : 'Search'}</button></form>{error && <p role="alert">{error}</p>}<div className="mt-8 space-y-3">{results.map(({ bot, matches }) => <button key={bot.id} className="search-result" onClick={() => onSelectBot(bot.id)}><span className="font-semibold">{bot.name}</span><p>{matches[0]?.text.slice(0, 180) || bot.role}</p><span className="text-xs text-zinc-500">{matches.length} matching messages</span></button>)}</div>{!results.length && <div className="panel-empty"><FiSearch /><h3>Find the thread</h3><p>Search by a phrase, question, or assistant name.</p></div>}</div>;
}
